### PR TITLE
Adapt to use Bootstrap 4 Beta 2 functions and variables

### PR DESCRIPTION
**Pull request by MWDelaney**

### CODE REVIEW

**Comment by LeoColomb** [comment]
This shouln't be inside https://github.com/roots/sage-installer?
Right now creating a new sage-project without using Bootstrap is broken... 😢

**Comment by MWDelaney** [comment]
We discussed this briefly and decided, since sage-installer is already a little behind, that this should go in Sage for now.

**Comment by retlehs** [comment]
hmm, might actually need to revisit this. this pattern unfortunately conflicts with the autoloading (that also ties into sage-installer) 🙁

**Comment by MWDelaney** [comment]
It's working for me on a Trellis example... or do you mean that we're compiling `functions` twice, which is ugly?

**Comment by MWDelaney** [comment]
Another option would be to structure `./autoload/_bootstrap.scss` like this, and remove `variables.scss` from `main.scss` entirely:

```css
// Bootstrap functions
@import "~bootstrap/scss/bootstrap";

// Sage variables
@import "common/variables";

// The rest of Bootstrap
@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/mixins";
@import "~bootstrap/scss/root";
@import "~bootstrap/scss/print";
@import "~bootstrap/scss/reboot";
@import "~bootstrap/scss/type";
@import "~bootstrap/scss/images";
@import "~bootstrap/scss/code";
@import "~bootstrap/scss/grid";
@import "~bootstrap/scss/tables";
@import "~bootstrap/scss/forms";
@import "~bootstrap/scss/buttons";
@import "~bootstrap/scss/transitions";
@import "~bootstrap/scss/dropdown";
@import "~bootstrap/scss/button-group";
@import "~bootstrap/scss/input-group";
@import "~bootstrap/scss/custom-forms";
@import "~bootstrap/scss/nav";
@import "~bootstrap/scss/navbar";
@import "~bootstrap/scss/card";
@import "~bootstrap/scss/breadcrumb";
@import "~bootstrap/scss/pagination";
@import "~bootstrap/scss/badge";
@import "~bootstrap/scss/jumbotron";
@import "~bootstrap/scss/alert";
@import "~bootstrap/scss/progress";
@import "~bootstrap/scss/media";
@import "~bootstrap/scss/list-group";
@import "~bootstrap/scss/close";
@import "~bootstrap/scss/modal";
@import "~bootstrap/scss/tooltip";
@import "~bootstrap/scss/popover";
@import "~bootstrap/scss/carousel";
@import "~bootstrap/scss/utilities";
```

I hate reproducing that much code, but in order to make things work the way I think we want (able to use Bootstrap functions in `variables.scss`, the array-merges for `$theme-colors` introduced in Bootstrap 4 beta 2 which are *awesome*, and still use autoloading) I think these are our options.

**Comment by retlehs** [comment]
> or do you mean that we're compiling functions twice, which is ugly?

actually that's not that bad..

i do think that we need to move all of the things into the bootstrap autoload file. it should also make it so that sage-installer wouldn't need any updates

would this work?

```
@import "~bootstrap/scss/functions";
@import "common/variables";
@import "~bootstrap/scss/bootstrap";
```

**Comment by MWDelaney** [comment]
@retlehs I'll try it and make another PR if it works!

**Pull request merged**
