### PR TITLE
Bump illuminate/support to 5.5

### PR DESCRIPTION
**Pull request by Log1x**
Some new goodies with the release of Laravel 5.5

### CODE REVIEW

**Comment by Log1x** [comment]
[`@switch`](https://laravel.com/docs/5.5/blade#switch-statements) seems to work as intended as well as everything else stock but I seem to get an error with trying to use the new [Custom If Statements](https://laravel.com/docs/5.5/blade#custom-if-statements).

**Example Code**
```
$sage = sage('blade')->compiler();

/**
 * Create @test() Blade directive
 */
$sage->if('test', function ($field) {
    return true;
});
```

```
@test 
   Hello
@endtest
```

results in:

```
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getEngineResolver() on null in /mnt/d/Development/web/sites/flux/web/app/themes/flux/vendor/illuminate/support/Facades/Blade.php on line 17
```

**Comment by patram1121** [comment]
The bump to 5.5 cased issues for my current project.  In the following blade template, the last @php (right before $link) did not convert to <?php in the blade cache.

Note sure if this is a 5.5 issue or there is a change I need to make with my code to make it compatible.

```
    @if (have_rows('acf_repeater))
      @php
        $count = 1
      @endphp
      <div class="col-sm-3">
          @while (have_rows('acf_repeater')) @php(the_row())
            @php
              $link = sanitize_title($title);
            @endphp
```

Was able to workaround by forcing 5.4 in composer:

```
"illuminate/support": "~5.4.0",
```

**Comment by Log1x** [comment]
Hmm. I did some testing and come across the same issue. It appears to be a problem with the shorthand PHP directive. I don't really understand what is causing it though. In some cases, it works just fine, but in others, not.

**Comment by webstractions** [comment]
I think you need a closing `@php` on the previous line:

```
@while (have_rows('acf_repeater')) @php(the_row()) @endphp
```
And FWIW, using this blade feature frequently may be a signal that you have too much logic embedded within your template. See [Blade Docs](https://laravel.com/docs/5.5/blade#php)

**Comment by webstractions** [comment]
@Log1x I am pretty sure there isn't an $app container in Sage. Thus the error. The `if()` method is running thru the Blade Facade and is trying to access `$app['view']` which doesn't exist.

```
   /**
     * Get the registered name of the component.
     *
     * @return string
     */
    protected static function getFacadeAccessor()
    {
        return static::$app['view']->getEngineResolver()->resolve('blade')->getCompiler();
    }
```

**Comment by webstractions** [comment]
Just dawned on me about the other Sage components, `sage-installer` and `sage-lib`, which also need to be bumped up to 5.5 as well. They are at ~5.4 for Illuminate dependencies for Console, Filesystem, Config, and wait for it, View.

Those two packages need to be updated for this PR to play nice.

**Comment by Log1x** [comment]
I'll give that a shot and do some testing and if all is well I'll do a PR over that way too so we can hopefully get this bumped.

**Comment by webstractions** [comment]
Sounds like a plan. Pretty sure that won't solve the custom if() statement though. You and @QWp6t talked about the App Container in #1932, which would fix this.

**Comment by webstractions** [comment]
@Log1x I have a 5.5 install running with no problems so far. Upgrading across the board (lib, installer, sage) doesn't have any ill effects.

The `if()` Blade directive is a sticky point. I am getting the same error that you did. In order to get around that, you have to install the complete Laravel package and create an App container. That would be going to far for what Sage is meant to be.

Coincidentally, this is not the first time something like this has come up (ie: cherry-picking Illuminate components). Take a look at Matt Stauffer's [Torch](https://github.com/mattstauffer/Torch). They have been trying to get Artisan support to work without downloading the entire package as well. 

This just won't work without Illuminate\Foundation, which doesn't have composer.json to install from. And weirdly, Laravel Lumen has it's own version of Artisan piecemealed together and is kind of flakey. Seems they couldn't get around that either.

**Comment by webstractions** [comment]
@Log1x I found a workaround for getting the Blade `if()` method to work!

In `setup.php` add the following to the Sage Setup options where the `singletons` for assets and Blade are being bound to the container. 

```php
    // Set the Facade application container to the Sage Container
    \Illuminate\Support\Facades\Facade::setFacadeApplication(sage());
```
This not only fixes the `if()` method, but should allow us to use facades as well. The only thing missing is the AliasLoader, which is part of Illuminate\Foundation.

**Pull request closed without merging**
