### PR TITLE
Add WooCommerce support for Controller

### PR DESCRIPTION
**Pull request by darrenjacoby**
Passing the data to woocommerce allows Controller to use the data in WooCommerce template files.

### CODE REVIEW

**Comment by darrenjacoby** [comment]
App.php passes the variables to all pages, and not be overridden using the Controller hierarchy, which may not be ideal.  The above is checking if it's a WooCommerce template, and then adding those to woocommerce.blade.php which gets the WooCommerce template from woocommerce/.  It also allows users to have a SingleProduct.php Controller file for example. 

I haven't looked into `woocommerce_template_loader_files`, am I missing something there? I've based the above solution on this issue, https://github.com/soberwp/controller/issues/16

**Comment by QWp6t** [comment]
Yeah, so far in all my tests, I've been able to get this to work without any issues. I'm not really sure which method you guys are using to make your theme support WooCommerce, but I used a few different techniques. The easiest to hook into `woocommerce_template_loader_files` and tell it to look for `woocommerce.blade.php`, but if you want the increased granularity of single-product, archive-product, etc., then you can hook into `woocommerce_locate_template` and return `template_path($template)`. (You can do the same with `wc_get_template_part` to include WooCommerce partials.)

The former will make controller/Woocommerce.php available while the latter will make controller/SingleProduct.php available.

For what it's worth, WooCommerce recommends making use of template hooks instead of overwriting their template files. But I will still document all of this before Sage 9 launches.

**Comment by darrenjacoby** [comment]
@QWp6t thanks!  That information is def all helpful!

**Comment by mtx-z** [comment]
I found a way to pass correctly all variables to Woocommerce Views, don't know if it's the right way but it works as for now : https://discourse.roots.io/t/controller-and-woocommerce/9469/5

**Pull request closed without merging**
