### PR TITLE
Fixes compatibility HMR & Browser Sync with external clients and IE

### PR DESCRIPTION
**Pull request by nicooprat**
Polyfills for IE (tested with IE10+):

* Promise
* EventSource

Fix:

When developing with external clients (`192.168.xx.xx:3000`), HMR could not replace styles because the URL would be replaced by `localhost:3000`, so the `hot-update.json` file returned a 404. Here's a simple workaround, that could certainly be enhanced ([related to this issue](https://github.com/webpack/webpack/issues/443)).

Hope it helps!

PS. Related to this issue https://github.com/roots/sage/issues/1874

### CODE REVIEW

**Comment by QWp6t** [comment]
You should be able to make use of `SAGE_DIST_PATH`, as documented here: https://github.com/roots/sage/blob/master/resources/assets/build/config.js#L36-L44

```sh
SAGE_DIST_PATH=192.168.xx.xx:3000/app/themes/sage/dist yarn start
```

Something like that.

I'm closing this for the time being, but feel free to reopen it if you want to try to resubmit a PR that uses the existing solutions we've come up with for this issue (albeit our solutions did not have local development in mind at the time). In the meantime, I'll be looking into this as well.

**Comment by nicooprat** [comment]
Ok thanks, I'll try it. Would it be possible to use the `.npmrc` file to override this kind of configuration? `DEVURL` would be another example, it's pretty useful when working on multisites, but not really handy to write it every time before the command.

**Comment by QWp6t** [comment]
You could edit it in package.json

```json
  "scripts": {
    ...
    "start": "SAGE_DIST_PATH=192.168.xx.xx:3000/app/themes/sage/dist webpack --hide-modules --watch --config resources/assets/build/webpack.config.js",
    ...
  },
```

But that's less than ideal because the IP could change. But that issue isn't alleviated by hard-coding it in .npmrc or anywhere else.

With the next version of Sage, we'll be supporting config-local.json, which will allow you to override config.json settings (the idea being that these are things each particular dev on your team might want to change depending on their development environment, such as proxy URL, dev URL, etc). In which case you could just use config.enabled.watcher to check if you're in watch mode, and if so, then set SAGE_DIST_PATH to the IP address you specify in config-local.json.

In the meantime, you can do all of this in config.js

If you need further help, please post on https://discourse.roots.io/

**Comment by nicooprat** [comment]
Thanks. +1 for local git-ignored file.

For now, anyone interested in storing `DEVURL` in a git-ignored file could just add this line to `.npmrc` at the root of your project: `DEVURL=http://yoursite.dev` and replace this one in `webpack.config.watch.js`: `const target = process.env.npm_config_DEVURL || process.env.DEVURL || config.devUrl;`

**Pull request closed without merging**
