### PR TITLE
Sage 9-alpha.4

### PR DESCRIPTION
**Pull request by QWp6t**
I haven't done a whole lot of testing with this so I don't wanna push it as an update just yet. 

Will do some more tests and tag a new release probably sometime this week. If all goes well with this release, then the next step is adding Blade support.

## If you decide to test this, be sure to re-activate your theme.

### CODE REVIEW

**Comment by QWp6t** [comment]
This PR closes: #1715, #1719, #1739, #1741, #1742, #1743

**Comment by nathanielks** [comment]
Just tested this on a theme I'm working on. Javascript is loading, but for some reason styles aren't being compiled?

**Comment by JonMasterson** [comment]
I encountered an issue related to the 'stylesheet' > 'template' revision in functions.php (not using Bedrock). With the 'template' change, theme name was missing from my css/js paths. Also, image assets went missing — image file paths (which should point to '/dist/images') contained '/templates/' in the file path. When I reverted functions.php, all was well.

**Comment by QWp6t** [comment]
@nathanielks 
If you mean they're not written to your filesystem when you do `npm start`, that's because they're in webpack's internal filesystem, which sits in memory. This is faster. When you visit the proxy server, they should still be served.

@JonMasterson 
You just have to reactivate your theme. That will solve your issue.

**Comment by nathanielks** [comment]
@qwp6t yup, I'm aware! The stylesheets weren't loaded even when visiting the proxy. I'll test a vanilla clone and see what that gives me

**Comment by JonMasterson** [comment]
Doh! Didn't notice the hook — Works great. Thanks!

**Comment by giacomoalonzi** [comment]
@nathanielks same problem here, let me know if you solve it! thx

**Comment by retlehs** [comment]
@giacomoalonzi try removing your `node_modules` directory and switching to yarn

**Comment by nathanielks** [comment]
@retlehs @giacomoalonzi I was already using `yarn` and nuked `node_modules` to no avail... an interesting clue is the output for `yarn start` in alpha4 for me does not include any of the standard Webpack jargon and doesn't appear to run anything when I save a file that _would_ trigger an update in alpha3.

**Comment by nathanielks** [comment]
Mmmm'k. Vanilla alpha4 _does_ have the webpack jargon, so I'm believing I didn't merge everything correctly. I had a bunch of merge conflicts trying to merge 3 and 4 in an existing theme, so it was a bunch of manual merge resolution.

**Comment by nathanielks** [comment]
Welp, insert foot into mouth. It works fine! The only difference for me is the Webpack hullabuhloo still isn't being output in `yarn start`, but it does in fact perform updates in the browser.

**Comment by nathanielks** [comment]
Now, one thing that I have noticed (that's semi annoying) is that on subsequent rebuilds without refreshing the page, updated JS isn't really because the router is only loaded on document.ready() (this also existed in alpha3). @QWp6t is the solution here to have it trigger on document.ready and on rebuilds? Does HMR broadcast any events we can hook into? I'm just not sure where to start. I imagine we'll have to have some method of removing event listeners as well before the code is evaluated...

**Comment by nathanielks** [comment]
Oh, and for whatever reason even reloading the page doesn't update the js. I have to `ctrl-c` `yarn start` and restart it to get the updates in the browser.

**Comment by QWp6t** [comment]
@nathanielks 

I'm not sure if there's an event, but this should work:
```
if (`module.hot`) {
  new Router(routes).loadEvents();
}
```

Obviously an event would be better, though.

**Comment by derkjn** [comment]
Side note, this is already not compatible with `webpack@2.1.0-beta.26`.
The `package.json` should be updated accordingly.

**Comment by wassimdotis** [comment]
I can't get isotope and a couple of other scripts to work with DOM ready. What was the reason for 724d550739c73a561ab80f9d12add89fb78a7c8c ?

**Comment by derkjn** [comment]
Tested this today on a fairly big project with lots of other deps and stuff. All working good on my end! Cheers @QWp6t!

**Pull request merged**
