### PR TITLE
Better support for VSCode, Prettier, JSDoc, Eslint combo

### PR DESCRIPTION
**Pull request by benpsnyder**

### CODE REVIEW

**Comment by Log1x** [comment]
Hi! Thanks for the PR's.

The yarn PR looks great and we'll handle it there moving forward, but the VSCode support is a little too out of scope for what we have in mind going forward with Sage 10.

**Comment by benpsnyder** [comment]
Cool... thanks @Log1x. Kindly let me know what is out of scope as this is simply supporting an IDE?

**Comment by Log1x** [comment]
IDE-specific customizations just aren't something we're looking to support out of the box.

**Comment by benpsnyder** [comment]
OK 👍  ... you gents are the core maintainers so I will respect it. I think its low-hanging fruit that invites more contributions 👯 

I have done a lot of work over in the @nrwl/nx community and there are many times when I include Wordpress front-end codebases into my Nx monorepos for clients.  I would like to start contributing more to your sage base theme so we can convert more themes for client sites that work better with apps in Nx repos.  Almost all of our tooling is based on VSCode as an IDE.

Food for thought :D

Will contribute anyway, and just cherry-pick when preparing a branch for a PR.

**Pull request closed without merging**
