### PR TITLE
travis: PHP 7.0 nightly added

### PR DESCRIPTION
**Pull request by TomasVotruba**
See http://docs.travis-ci.com/user/languages/php/#PHP-7

### CODE REVIEW

**Comment by ntwb** [comment]
As `7.0` is only an alias of `nightly` and that PHP 7.0 has not yet been released I'd suggest you use `nightly` and allow these tests to fail.

For reference see WordPress' Core commit for the same: https://core.trac.wordpress.org/changeset/31558/

**Comment by TomasVotruba** [comment]
Good points, I've implemented them.

**Comment by retlehs** [comment]
not sure if we need this now, but please update the PR to use 2 spaces instead of 4

**Comment by TomasVotruba** [comment]
@retlehs Fixed

**Comment by QWp6t** [comment]
:+1:

It's a good idea to test future versions so we know what kind of issues to be cognizant of.

**Comment by retlehs** [comment]
thanks yall

**Comment by TomasVotruba** [comment]
Thanks!

**Pull request merged**
