### PR TITLE
Conversion from Bootstrap to Material Design Lite

### PR DESCRIPTION
**Pull request by peiche**
Changes to basic markup, stylesheets, and config files to support importing MDL via bower.

### CODE REVIEW

**Comment by retlehs** [comment]
nice. it's amazing how easy that is

**Comment by peiche** [comment]
Submitting a pull request against roots/sage master was a mistake. The master branch of https://github.com/peiche/sage-mdl is perfectly usable, though.

**Comment by retlehs** [comment]
no problem. thanks for sharing that. do you mind posting a thread on https://discourse.roots.io?

**Comment by retlehs** [comment]
oops, i see you already did. :blue_heart:

**Pull request closed without merging**
