### PR TITLE
Add stylelint to builds and watch

### PR DESCRIPTION
**Pull request by samrap**
[Stylelint](https://stylelint.io/) is an awesome tool that brings the many benefits of linting to CSS and Sass. In Sage, we already use Eslint for JavaScript and PHPCS for the back end. I find that often times, our Sass files are left with no coding standards. Poorly written Sass can be very difficult to understand and can leave you with unforeseen bugs and duplicate code.

This PR adds Stylelint to the build and watch processes via the [stylelint-webpack-plugin](https://github.com/JaKXz/stylelint-webpack-plugin) and extends [Stylelint's recommended config](https://github.com/stylelint/stylelint-config-standard) as a base. To be friendly for CI builds, Stylelint will fail on error when running a build, but will only emit errors while watching, ensuring that it does not break the watch task. 

Adding Stylelint is a no-brainer. However, the implementation could use some discussion. The easiest way is with the stylelint-webpack-plugin which seems to have a smaller community and moderate support at best. I am willing to discuss other options, but have been used the plugin on development of 4 highly custom sites across my team with no issues. It has really helped clean up our Sass code style as a whole!

### CODE REVIEW

**Comment by QWp6t** [comment]
Looks like we're on board with this. Just need to review some of the stuff it enforces. :+1:

**Comment by samrap** [comment]
Sounds good. Stylelint is very similar to eslint in that you can override rules straight in the `.stylelintrc`. Let me know if you would like any help getting this merged!

**Comment by retlehs** [comment]
thanks a lot for this PR! and thanks for doing that push access to your branch thing (i made one minor update w/ the comments in sass files and fixed a conflict on the yarn lockfile)

**Comment by levito** [comment]
@samrap I like it! Could you please resolve the conflict in yarn.lock?

@QWp6t would you please merge this soon?

**Comment by samrap** [comment]
Happy to help! Thanks for all your hard work on Roots!

**Pull request merged**
