### PR TITLE
Removed outdated meta content for internet explorer compatibility mode.

### PR DESCRIPTION
**Pull request by robbintt**
Issue: https://github.com/roots/sage/issues/1538

### CODE REVIEW

**Comment by QWp6t** [comment]
We tend to defer to H5BP for this stuff. 

* https://github.com/h5bp/html5-boilerplate/blob/v5.0.0/src/index.html#L5
* https://github.com/h5bp/html5-boilerplate/pull/1673
* https://github.com/h5bp/html5-boilerplate/blob/master/src/doc/html.md#x-ua-compatible

As long as they still have this, we probably will too, especially since it's super simple to just delete a single line. We could maybe document it (if we haven't already) to let users know that we recommend removing that line and setting it in server configs.

**Comment by robbintt** [comment]
Sure, that's reasonable.  It would be great to have an explanation in the README.md regarding where H5BP is deferred to if it's simple enough to explain.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (118/100 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:50435 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaYq8-002Pbs-0I
	for greg@biomassiv.es; Fri, 11 Sep 2015 19:38:49 -0500
Date: Fri, 11 Sep 2015 17:38:51 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442018331;
	bh=5TjxxQOtFSIqone/5pkgCK9MBuFtSzgDReiG/gwkWrQ=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=j7Vt+3PpKqel5pxiRjWBflhcpwheKTnjqnnZmgbpPsghlnJd6d8vWcvR9ddLRlVYJ
	 bm9f2/8/2B0EtTWGcr8owf+oiZRqwI1Isdsnjy475MIEQdUv3lshtOGRREvq9t+Ybw
	 BbtRQfE2keEcb1MYR2RZRzgU8YCqAQdZYBQcvQdo=

**Comment by retlehs** [comment]
already mentioned on https://roots.io/sage/docs/theme-templates/:

> The markup in Roots is based off HTML5 Boilerplate

**Pull request closed without merging**
