### PR TITLE
🔧 Acorn v3 (Laravel 9.x), drop PHP 7.4 support

### PR DESCRIPTION
**Pull request by retlehs**
These changes are required to upgrade to Acorn v3

TODOs

* [x] Acorn v3 stable release
* [x] [Upgrade docs](https://roots.io/acorn/docs/guides/upgrading-acorn/) (https://github.com/roots/docs/issues/433)

Ref https://github.com/roots/acorn/releases

### CODE REVIEW

**Comment by Striffly** [comment]
Any update for this ? Some dependencies (like `php-ffmpeg`) seems to not be compatible with `roots/acorn v2` :
```text
Fatal error: Declaration of Illuminate\Container\Container::has($id) must be compatible with Psr\Container\ContainerInterface::has(string $id): bool in /app/vendor/illuminate/container/Container.php on line 194
```
Upgrading to `roots/acorn v3` seems to resolve this issue, but [we can't show any view for the moment...](https://discourse.roots.io/t/target-class-sage-view-does-not-exist/23813)

**Comment by retlehs** [comment]
> Upgrading to roots/acorn v3 seems to resolve this issue, but [we can't show any view for the moment..](https://discourse.roots.io/t/target-class-sage-view-does-not-exist/23813)

What update are you looking for? This PR demonstrates how to correctly upgrade to Acorn v3 and doesn't contain the error that you're describing. It's not going to be merged until Acorn v3 has a stable release.

**Comment by Striffly** [comment]
After upgrading, I got this error too : `Target class [sage.view] does not exist.`

**Comment by Log1x** [comment]
> After upgrading, I got this error too : `Target class [sage.view] does not exist.`

Double check your `ThemeServiceProvider` making sure it extends `SageServiceProvider` and has `parent::` calls to `register()` and `boot()` if they are present. You can reference my [latest commit](https://github.com/roots/sage/pull/3097/commits/4bff0813fb705767a057c2a11bbdb384ccd0f594).

**Pull request merged**
