### PR TITLE
Allow `debugger` statements in development JS

### PR DESCRIPTION
**Pull request by austinpray**
fixes https://github.com/roots/sage/issues/1480

cc @aaemnnosttv

### CODE REVIEW

**Comment by austinpray** [comment]
I need some help with the decision to fail the JSHint task. 

When JSHint fails:
- what should happen when in development mode?
- what should happen when in `--production` mode?

I was thinking that JSHint should give "by the way" warnings in development but fail production builds. But I'm unsure if this is the way to go. Really would appreciate feedback.

On one hand it makes sure no bad/dangerous code makes it to production. On the other: if you ignore the development JSHint warnings you will be unable to deploy until you pay the JSHint debt.

**Comment by Foxaii** [comment]
The "by the way" warnings are a good idea. One long list of all the changes that need attention is better than just the first fault that has caused the build to fail.

I agree with your thinking that it should be a fail in `--production` as well. Perhaps document that they need to run in development mode to list the fixes required.

**Comment by JulienMelissas** [comment]
I agree with @Foxaii - I think it's best if during development it just provides warnings, and during production it should fail. Documentation is a good think to bring up too, thanks for mentioning that!

**Comment by austinpray** [comment]
>Perhaps document that they need to run in development mode to list the fixes required.

@Foxaii: in both cases it lists all the errors you need to fix. The only difference is that the production build will fail to compile.

**Comment by Foxaii** [comment]
Nice to know but that doesn't change my agreeing with you, @austinpray.

**Comment by austinpray** [comment]
ping @aaemnnosttv, curious to see what you think about this.

**Comment by aaemnnosttv** [comment]
@austinpray I think it's a great solution.  Great job :+1:

**Pull request merged**
