### PR TITLE
Update sage 9.x dependencies

### PR DESCRIPTION
**Pull request by strarsis**
This PR updates the dependencies of sage 9.x as far as possible without breaking the build process.

All dependencies have been updated as much as possible without breaking the build process or introducing too many configuration changes.

Related PR: https://github.com/roots/sage/pull/2569

### CODE REVIEW

**Comment by atoupet-toki** [comment]
Thanks for your good job! Seems that there is some warning during install :) 

`warning " > bootstrap@4.5.3" has incorrect peer dependency "popper.js@^1.16.1".
warning " > autoprefixer@10.0.1" has unmet peer dependency "postcss@^8.1.0".
warning " > eslint-loader@4.0.2" has incorrect peer dependency "eslint@^6.0.0 || ^7.0.0".
warning " > eslint-loader@4.0.2" has incorrect peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > file-loader@6.2.0" has incorrect peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > postcss-loader@4.0.4" has incorrect peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > postcss-loader@4.0.4" has unmet peer dependency "postcss@^7.0.0 || ^8.0.1".
warning " > sass-loader@6.0.7" has incorrect peer dependency "node-sass@^4.0.0".
warning " > stylelint-webpack-plugin@0.10.5" has incorrect peer dependency "stylelint@^8.0.0".
warning " > stylelint-webpack-plugin@0.10.5" has incorrect peer dependency "webpack@^1.13.2 || ^2.7.0 || ^3.11.0 || ^4.4.0".
warning " > url-loader@4.1.1" has incorrect peer dependency "webpack@^4.0.0 || ^5.0.0".`

**Comment by strarsis** [comment]
@atoupet-toki: During install indeed some warnings appear. But I can't find the bootstrap one (and I selected bootstrap as framework). Have you installed the latest sage 9.x?

**Comment by atoupet-toki** [comment]
@strarsis I just tried once again. I dont know if there were some cache but I got a few warnings but no bootstrap on my side too! :)

**Comment by jokanane** [comment]
I did a similar effort last week based on 9.0.9 and noticed that the following versions needs to be in place for `background-image('../images/svg/file.svg');` to work:

```diff
-    "file-loader": "^6.2.0",
+    "file-loader": "^1.1.6",

-    "resolve-url-loader": "^3.1.2",
+    "resolve-url-loader": "~2.3.1",
```

I am today merging an old Sage 8 theme to 9.0.10 and am seeing the same as last week:

```
Module not found: Error: Can't resolve...
```

Assets compile with the aforementioned changed package versions. What I am working on now is far from being ready so I can't say anything about how things actually look.

Apologies if I'm mistaken, but that's what I'll have to stick to for the time being.

**Comment by ecruhling** [comment]
i can confirm that having file-loader and resolve-url-loader at the higher versions in this commit (6.2.0 & 3.1.2 respectively) breaks the build process if you have any image files referenced in the CSS. it was breaking specifically for me in slick.js pulling in a background image

reverting file-loader and resolve-url-loader to previous versions and the build process works again

**Comment by atoupet-toki** [comment]
Same happens here. After some research, we need the latests versions of nodeJS for the new dependencies ...

**Comment by strarsis** [comment]
@atoupet-toki: You can use a node version manager like [`nvm`](https://github.com/nvm-sh/nvm) and just let it install the latest LTS version:
`nvm install lts/*`
`nvm use lts/*`
You can even add a `.nvmrc` file to the theme folder to lock in a specific node version (not just lts/*), 
so everyone that uses that project will use the same node version on which the build is known to work.

**Comment by atoupet-toki** [comment]
@strarsis Thank you I used once nvm but mever heard from .nvmrc files. I'll take a look at the whole thing thanks for the info!

**Comment by strarsis** [comment]
@atoupet-toki: Besides the usefulness of nvm for reproducible builds (among sytems and teams), 
there seems to be an issue that crops up caused by one of the updated dependency, I am looking into that.

**Comment by strarsis** [comment]
PR for fixes in sage 9: https://github.com/roots/sage/pull/2603

**Comment by strarsis** [comment]
https://discourse.roots.io/t/sage-9-2-please-test/20067/9

**Pull request merged**
