### PR TITLE
Remove unnecessary references to jQuery

### PR DESCRIPTION
**Pull request by retlehs**
no longer needed after #1422

### CODE REVIEW

**Comment by JulienMelissas** [comment]
Can't believe I forgot about this while I was looking through everything - good catch!

**Comment by JasonTheAdams** [comment]
So if it's not being loaded via bower, then how is jquery being loaded? Or did you just opt to let Wordpress do it the default way?

**Comment by austinpray** [comment]
I need to do some quick research on how to tell bower a dependency is included externally not via bower. Bower needs to know what version of jQuery we are using so people are prevented from installing  packages that require conflicting versions of jQuery.

@JasonTheAdams yes we use the default WordPress jQuery version.

**Comment by retlehs** [comment]
merging this for now. @austinpray you can follow up with another PR

**Comment by QWp6t** [comment]
@austinpray 

bower/bower#1394
bower/bower#927

**Pull request merged**
