### PR TITLE
Create prototype of GitHub Issue Template

### PR DESCRIPTION
**Pull request by chrisatomix**
Just trying to get the ball rolling on https://github.com/roots/sage/issues/1619

Inspired by several other GitHub Issue Templates, including [Yoast SEO](https://github.com/Yoast/wordpress-seo/blob/master/ISSUE_TEMPLATE.md).

Open to suggestions on this one. We probably wouldn't want to ask too much up front (such as making them list their WordPress plugins), but asking for OS and NPM/Node versions can be quite handy when troubleshooting.

Also looking for some good examples of Pull Request Templates, but I think the Roots team is going to be more qualified to set those up :smile:

### CODE REVIEW

**Comment by retlehs** [comment]
thank you for the PR! this looks good, but would you mind using the issue template from the trellis repo as a base instead?

https://github.com/roots/trellis/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by QWp6t** [comment]
Note that this should be inside of a `.github/` folder in the project root, i.e., `sage/.github/ISSUE_TEMPLATE.md`.

**Comment by chrisatomix** [comment]
Great suggestions! I've used the much nicer Trellis version as a base (and updated where applicable as best as I can). I've also moved it to the `.github` subdirectory, and rebased the PR.

Let me know if any further changes are needed, thanks!

**Comment by retlehs** [comment]
awesome, thanks!

**Pull request merged**
