### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/sage ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
We have also added a `postinstall` script to let people know after `npm|yarn install` that you are welcoming donations (optional). [[More info](https://github.com/OpenCollective/opencollective-cli)]
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by monkeywithacupcake** [comment]
You have several kinds of backers on Open Collective (tiers) - please check how they have been grouped into backers and sponsors, or reassign if you want to have all the groups show on the readme. I'm not sure what you prefer (similar to trellis and bedrock)

**Comment by retlehs** [comment]
hey there,

i was going to manually implement most of the things in this PR into this project after seeing them on some other projects, but i'm pretty picky 😬 and there's several things that bother me...

the backers/sponsors badges aren't flat like the rest of the badges & seem kinda awkward. if we could get a flat badge with the estimated yearly budget (or available budget) then that would be pretty awesome!

with this project we were planning on handling the post `npm install` functionality with our composer (php) `post-create-project-cmd` that already exists

other things:

* no control over opinionated avatar size/border type/border color (not really a big deal)
* no control over sorting or who is included in these images? backers are missing several people who have paid signficantly more money than the ones who are being shown
* can't remove 'become a backer/sponsor' buttons
* sponsors functionality is broken
  * where is kinsta's logo?
  * our other gold sponsor is being shown as a backer instead of a sponsor... 
  * not all sponsors should have their logos shown. see the notes on our sponsorship levels on the collective

**Comment by monkeywithacupcake** [comment]
Yes, I have a note on this one - you have several tiers...not just 'backers' and 'sponsors', so they do get split up when I try to automatically pull them. You could instead treat each "tier" with its own approach - using this PR as a rough guide.
 
For example, you can get the images of the folks in the Supporter tier with: 
https://opencollective.com/sage/tiers/supporter.svg?width=600&button=false
you can adjust width of the whole image, like I've done here with width, you can turn off the "become a backer" button with button= false
There are a few other options I show here, so you can customize:

https://opencollective.com/sage/tiers/supporter.svg?margin=10&avatarHeight=200&width=800&height=800&style=%27square%27&button=false

You can adjust the badges to your liking (see [shields](https://shields.io/) for options: 
https://opencollective.com/sage/supporters/badge.svg?style=for-the-badge

If you think people/orgs are placed in the wrong tier, you can see the data at: https://opencollective.com/sage/members/all.json

**Comment by monkeywithacupcake** [comment]
You can definitely take care of the post install in your custom way. the default is not perfect for every repo!

**Comment by monkeywithacupcake** [comment]
Also, I think the issue with multiple tiers also will affect your two other related repos.

**Pull request closed without merging**
