### PR TITLE
Upgrade to Controller 2.1.0

### PR DESCRIPTION
**Pull request by darrenjacoby**

### CODE REVIEW

**Comment by kaisermann** [comment]
I think you forgot to change the version in the `composer.json` :smiley:

**Comment by darrenjacoby** [comment]
@kaisermann haha yea, updated the fork now

**Comment by darrenjacoby** [comment]
@sagalbot nope

**Comment by runofthemill** [comment]
@retlehs the book will need updates in `/chapters/04-customizing-templates/blade-templates.html` =D

@darrenjacoby maybe consider adding a note in the https://github.com/soberwp/controller readme for anyone updating from 9.0.0-beta.4? took me a little bit to sort it out and I could see lots of support requests in GH/Discourse :P

**Comment by darrenjacoby** [comment]
@runofthemill yea, good idea, I'll add an updating to 2.0.x section on the readme tomorrow.

**Comment by MWDelaney** [comment]
Are we not bringing in Controller 2.0.1 for a reason at this point?

**Comment by darrenjacoby** [comment]
@MWDelaney 

I think there may be some hesitancy based on 2.0.1 because of PSR4 Loading? I've since added upgrading information to the readme. If we are updating, which I would recommend, I'd like to tag a new release which has been tested on dev-master for a while now. It'll addresses some existing issues., happy to update this PR too.

**Pull request merged**
