### PR TITLE
Bootstrap 4 alpha

### PR DESCRIPTION
**Pull request by retlehs**
bootstrap released bs4 alpha today, and now you can test it with wordpress & sage by using this branch! here's some more info:

* http://v4-alpha.getbootstrap.com/
* http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/

if you take a look at the files changed on this PR, you can see that there's really not any big changes

### CODE REVIEW

**Comment by kilinkis** [comment]
thanks!

**Comment by retlehs** [comment]
@kilinkis there's a few different ways: 

* clone the git repo and then switch to the `bootstrap-4` branch
* [download a zip](https://github.com/roots/sage/archive/bootstrap-4.zip)
* use the [clone in desktop](https://github.com/roots/sage/tree/bootstrap-4) button

**Comment by kilinkis** [comment]
@retlehs thanks! I was about to clone it cuz I couldn't find the zip button. Anyway, thanks man! I love this project :)

**Comment by fgilio** [comment]
Good news! Thanks for the heads up

**Comment by retlehs** [comment]
there's new issues that have popped up because of this: https://github.com/twbs/bootstrap/pull/17494

bootstrap 4 now requires jquery 2.x.x in order for the JS to work

**Comment by aaemnnosttv** [comment]
@austinpray Is it possible to use both versions of jQuery using Webpack?  Ie: Bundling the twbs js separately with jQuery 2.x?

**Comment by retlehs** [comment]
jquery 2 issue has been resolved upstream! alpha 2 is out, i'll rebase this branch with master this week

http://blog.getbootstrap.com/2015/12/08/bootstrap-4-alpha-2/

**Comment by retlehs** [comment]
this branch is now up to date with master

**Comment by erikbelusic** [comment]
i just came across a new issue where i get the following in the console - Uncaught Error: Bootstrap tooltips require Tether (http://github.hubspot.com/tether/) but never got it before. i assume this is new in alpha 2? because we concatenate all js into main.js the error is blocking my js from running. i know i can include the tether library before, but if not using the parts of bootstrap that require it, its extra overhead

**Comment by retlehs** [comment]
ugh. they should be adding it as a bower dep... 

https://github.com/twbs/bootstrap/issues/17273#issuecomment-162023348

**Comment by retlehs** [comment]
https://github.com/twbs/bootstrap/issues/17325

**Comment by retlehs** [comment]
https://github.com/twbs/bootstrap/pull/18575

**Comment by retlehs** [comment]
closing this PR as we're not going to keep up with bs4 on sage 8. see [sage 9](https://github.com/roots/sage/tree/sage-9) / #1590

**Pull request closed without merging**
