### PR TITLE
Add 'config.enabled.browserSync' option to Webpack configuration

### PR DESCRIPTION
**Pull request by pboi20**
This adds a configuration option to disable BrowserSync (and Wepack HMR) and support a more basic "watch and manually refresh" kind of workflow.

**Example**

In `resources/assets/config.json`, add:

```
  "enabled": {
    "browserSync": false
  }
```

Run `yarn start`:

yarn-start

Update something in `resources/assets/styles/main.scss`:

update-main-scss

### CODE REVIEW

**Comment by GeorgeGedox** [comment]
Yes, please, yes. Let us disable browsersync and HMR, why is there no `yarn watch` option without this bloat?

**Comment by pboi20** [comment]
Hey @GeorgeGedox , thanks for your interest! To be fair, I think that everyone is focused on Sage 10 now, where disabling Browsersync is as simple as commenting out 1 line in `webpack.mix.js`.

Who knows, maybe this patch will make it in a future maintenance release of Sage 9 :)

**Comment by ColeyG** [comment]
This has caused me many problems dealing with Sage. I hope to god this gets merged

**Comment by badcrocodile** [comment]
I'd LOVE to disable Browser Sync. It drives me mad that I add/edit rules in dev tools then watch them all get blown away when the sync runs. However when implementing these changes I end up with an "Unable to Connect" error. New to Sage, any ideas?

**Comment by tstocker-iris** [comment]
Common this should be necessarily merged

**Pull request closed without merging**
