### PR TITLE
fix(bundle-editor): remove `@wordpress/edit-post`

### LINKED ISSUE #2919: Bug: Fatal error on wp-admin widgets
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

`/wp-admin/widgets.php` has a fatal error

### Steps To Reproduce

1. Visit `/wp-admin/widgets.php`

### Expected Behavior

wp-admin should load

### Actual Behavior

```
ErrorException (E_USER_NOTICE)
wp_enqueue_script() was called <strong>incorrectly</strong>. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.8.0.)
```

### Relevant Log Output

_No response_

### Versions

10.0.0-beta.2

### PR DESCRIPTION
**Pull request by retlehs**
closes #2919

### CODE REVIEW

**Comment by kellymears** [comment]
there are 17,775 issue results for `@wordpress/edit-post` in the gutenberg repo. https://github.com/WordPress/gutenberg/search?q=%40wordpress%2Fedit-post+is%3Aissue&type=issues

When I first wrote this it was a requirement in order to load `registerBlockStyle` and `unregisterBlockStyle`. Almost impossible to review if that is no longer the case. 

I'll check and make sure this doesn't break that and what workarounds we might have if it does.

**Comment by kellymears** [comment]
Related issue: https://github.com/WordPress/gutenberg/issues/9757

May have been fixed for us in: https://github.com/WordPress/gutenberg/pull/34299

**Comment by retlehs** [comment]
@kellymears `registerBlockStyle` and `unregisterBlockStyle` are both working as expected with this PR, is there any reason why this can't be merged?

tbh i'm not super interested in waiting on gutenberg fixes to work their way into wp core if we can merge and fix this now

**Comment by kellymears** [comment]
no, its good to merge!

**Review by kellymears — APPROVED** [review]

**Pull request merged**
