### PR TITLE
Ensures gulp concatonates sources in order

### PR DESCRIPTION
**Pull request by austinpray**
closes https://github.com/roots/sage/issues/1476

Make the bower file paths relative due to
https://github.com/sirlantis/gulp-order/issues/11

### CODE REVIEW

**Comment by austinpray** [comment]
https://discourse.roots.io/t/internet-explorer-8-ie8-compatibility/3596/13?u=austin

**Comment by austinpray** [comment]
@retlehs gonna merge

**Comment by retlehs** [comment]
not sure about depending on that project, doesn't really look maintained. not a fan of the `makeRelative` function because it doesn't seem like the linked issue is going to be resolved

**Comment by retlehs** [comment]
waiting on https://github.com/austinpray/asset-builder/issues/49

**Comment by retlehs** [comment]
we won't be addressing this :warning:

**Pull request closed without merging**
