### PR TITLE
Fix injection issues

### PR DESCRIPTION
**Pull request by QWp6t**
This should hopefully fix issues with browser-sync not refreshing or injecting when changes are made to template files.

Note that we are no longer passing the copy glob to browser-sync. We are only passing php files to it. Webpack handles everything else.

Still a couple of issues to address:

- [x] (upstream) [Problems with SSL](https://discourse.roots.io/t/watching-blade-files-in-sage-9-beta-2/8816/21)
- [x] [Compatibility issue with Tailor](https://discourse.roots.io/t/sage-9-beta-2-tailor-editor-giving-view-error/9003) (wontfix? - seems to be a non-issue to me, just briefly shows an error message but works fine thereafter)

### CODE REVIEW

**Comment by derkjn** [comment]
Tested this this morning, all seems to be working fine on my end as far as I can tell!
Thanks for the fix @QWp6t!

**Comment by apintocr** [comment]
I confirm this is working after the latest commit 419863ee9355f477d3baad949c2edd2a7b232142
However the JS might need to be reloaded after as, for example, select2 stops working after the HTML injection takes place.

**Comment by TrayWeb** [comment]
Hi Guys,

I still have the same issue on a fresh install of sage 9 beta 3.
CSS files work well but not the blades.

Does anyone still have the same issue ?

**Comment by apintocr** [comment]
This commit solved the issue on my previous project, however a fresh install I still have the same issue.

**Comment by QWp6t** [comment]
What version of node are you using?

**Comment by TrayWeb** [comment]
Thanks for the reply:

v7.8.0
****

**Comment by QWp6t** [comment]
I think they removed or renamed the environment variable for 7.x, but I haven't had a chance to look up how it should be done now.

The last I had read about it was in this discussion: https://github.com/nodejs/node/issues/5258

**Comment by TrayWeb** [comment]
Hello Guys,
Fixed the issue by changing the watch part on my config.json:

```
  "watch": [
    "resources/views/partials/*.blade.php",
    "resources/views/layouts/*.blade.php",
    "resources/views/*.blade.php"
  ],
```

**Comment by apintocr** [comment]
@TrayWeb not working for me :(

**Comment by TrayWeb** [comment]
Can you please send your config.json file and also the structure of your files ?
Does it work for the css ?

**Comment by apintocr** [comment]
@TrayWeb it's a clean sage install using the latest commits from the repository.

Anyway, here's my config.json
```
{
  "entry": {
    "main": [
      "./scripts/main.js",
      "./styles/main.scss"
    ],
    "customizer": [
      "./scripts/customizer.js"
    ]
  },
  "publicPath": "/app/themes/themename",
  "devUrl": "https://site.dev",
  "proxyUrl": "https://localhost:3000",
  "cacheBusting": "[name]_[hash:8]",
  "watch": [
    "{app,resources/views}/**/*.php"
  ],
  "browsers": [
    "last 2 versions",
    "android 4",
    "opera 12"
  ]
}
```

I've also tried with your code, no change.

**Comment by apintocr** [comment]
Funny enough I have another project, also with sage (beta-3 here), that has EXACTLY the same webpack files and configuration, it's using the same Trellis vagrant box and it works...

**Comment by waylay** [comment]
@TrayWeb Thanks! Worked for me! This is what I used:

```
  "watch": [
    "app/*.php", 
    "resources/views/**/*.php", 
    "resources/views/*.php"
  ]
```

**Comment by coffeeneed** [comment]
Thanks, @TrayWeb 
I also experienced this problem and can confirm that this worked;

Changing from:

```
  "watch": [
    "{app,resources/views}/**/*.php"
  ]
```

too:
```
  "watch": [
    "resources/views/partials/*.blade.php",
    "resources/views/layouts/*.blade.php",
    "resources/views/*.blade.php"
  ]
```

Any chance a fix for this will be commited to master any time soon?

**Comment by v3nt** [comment]
was this ever fixed? Started a new project and still not watching blade files.

**Pull request merged**
