### PR TITLE
Fixed production manifest path

### PR DESCRIPTION
**Pull request by derkjn**
Fixes the issue described in [#1880](https://github.com/roots/sage/issues/1880).

### CODE REVIEW

**Comment by QWp6t** [comment]
lol oops

**Comment by QWp6t** [comment]
Thanks for the PR!

**Comment by derkjn** [comment]
No worries at all :)
Thank you for the awesome job!! Your changes have been inspiring me for the last few months, I'm glad I can contribute to this project for once! 😄

**Comment by MWDelaney** [comment]
Definitely ran into this on a deploy tonight. Spent ten minutes going "Bwaaahhh?" and then found this PR. Thanks for the fix, @derkjn!

**Comment by lekkerduidelijk** [comment]
Woah thanks a lot! Had the same deploy issues as @MWDelaney 😅

**Pull request merged**
