### PR TITLE
Add support for theme customizer

### PR DESCRIPTION
**Pull request by retlehs**
two new files:

* `lib/customizer.php` — add postmessage support and enqueue customizer js
* `assets/scripts/customizer.js` — js for the theme customizer. currently changes the site name in the header when it's updated from the customizer

### CODE REVIEW

**Comment by JulienMelissas** [comment]
Looks great. Thanks for doing this @retlehs!

(thanks for the inspiration @stevenslack)

**Comment by retlehs** [comment]
what this PR does: 

sage-customizer

use it as a start for getting your theme customizer setup how you want. here's a quick example of something i'm working on — using the customizer to change up some colors:

customizer-carrot

**Comment by ciromattia** [comment]
+1
Great, I use customizer for all the site-wide options and at the moment I'm putting the whole bunch of code into setup.php.
Is the JS really needed?

**Comment by retlehs** [comment]
@ciromattia yep, the JS is needed to make use of the real time preview

**Comment by jo4nny8** [comment]
Does anyone have a working example of being able to change the theme colours using the customizer?

I've been trying to achieve it with leafo scssphp compiler but I'm struggling.

**Pull request merged**
