### PR TITLE
Remove $content_width

### PR DESCRIPTION
**Pull request by retlehs**

### CODE REVIEW

**Comment by swalkinshaw** [comment]
Good riddance

**Comment by kalenjohnson** [comment]
Happy days

**Comment by austinpray** [comment]
Where were you when $content_width was removed? Never forget

**Comment by JulienMelissas** [comment]
Bye `$content_width` - you won't be missed.

**Comment by corradomatt** [comment]
Not that I mind, but why remove it now? Did I miss a discussion somewhere along the way?

**Comment by JulienMelissas** [comment]
@corradomatt - there are a few reasons, and we did have a few conversations here and there (can't find records of it right now), but in general, it's because it's really not necessary, and can cause some issues and general confusion.

Here's a good resource on that: https://wycks.wordpress.com/2013/02/14/why-the-content_width-wordpress-global-kinda-sucks/

**Comment by corradomatt** [comment]
Thanks for sharing that @JulienMelissas - makes sense to me.

**Pull request merged**
