### PR TITLE
Add version to main.js and main.css

### PR DESCRIPTION
**Pull request by diego-betto**

### CODE REVIEW

**Comment by knowler** [comment]
This is unnecessary since the files are already being versioned on the production build. Run `yarn build:production` to see what I mean.

**Comment by diego-betto** [comment]
Yes, it's correct. But when using `yarn build` in remote development server many times browser is not requesting correct version.

**Comment by QWp6t** [comment]
You can permanently enable cache-busting like this:

**resources/assets/config.json**
```json
{
  "enabled": {
    "cacheBusting": true
    }
}
```

If you want to add logic to it, then edit it in [config.js](https://github.com/roots/sage/blob/master/resources/assets/build/config.js#L27)

**Comment by diego-betto** [comment]
Awesome, thank you!

**Pull request closed without merging**
