### PR TITLE
Remove php blade shorthand

### PR DESCRIPTION
**Pull request by ttamnedlog**
Looks like a few leftover shorthand php directives.

### CODE REVIEW

**Comment by retlehs** [comment]
thank you!

**Comment by pi-mont** [comment]
Just wondering, is there a reason we shouldn't be using PHP shorthand directives in our templates?
Thanks

**Comment by Log1x** [comment]
It annoyingly got deprecated. :(

**Comment by retlehs** [comment]
see #2012 #2042

**Comment by garrettw** [comment]
See https://github.com/roots/sage/pull/2042

**Pull request merged**
